version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    assignees: ["BigTava", "leonardocustodio", "ba1uev", "justraman"]
    reviewers: ["BigTava", "leonardocustodio", "ba1uev", "justraman"]
    labels: ["dependencies"]
    groups:
      npm-packages:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    assignees: ["BigTava", "leonardocustodio", "ba1uev", "justraman"]
    reviewers: ["BigTava", "leonardocustodio", "ba1uev", "justraman"]
    labels: ["dependencies"]
    groups:
      gh-actions:
        patterns:
          - "*"
